const express = require('express');
const router = express.Router();
const workerController = require('../controllers/workerController');
const upload = require('../middlewares/upload');
const authMiddleware = require('../middlewares/authMiddleware');

// Protect all worker routes
router.use(authMiddleware);

/**
 * @swagger
 * components:
 *   schemas:
 *     Worker:
 *       type: object
 *       required:
 *         - name
 *         - photoUrl
 *         - jobRole
 *         - place
 *         - contactNumber
 *         - dailyWage
 *       properties:
 *         name:
 *           type: string
 *         photoUrl:
 *           type: string
 *         faceData:
 *           type: string
 *           description: Face embeddings or AI specific data
 *         jobRole:
 *           type: string
 *           description: Job role of the worker
 *         place:
 *           type: string
 *           description: Work location or site
 *         contactNumber:
 *           type: string
 *           description: Contact number
 *         dailyWage:
 *           type: number
 *           description: Daily wage of the worker
 */

/**
 * @swagger
 * /api/workers:
 *   get:
 *     summary: Retrieve a list of workers
 *     responses:
 *       200:
 *         description: A list of workers.
 */
router.get('/', workerController.getAllWorkers);

/**
 * @swagger
 * /api/workers/{id}:
 *   get:
 *     summary: Retrieve a single worker by ID
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *         description: Worker object.
 */
router.get('/:id', workerController.getWorkerById);

/**
 * @swagger
 * /api/workers:
 *   post:
 *     summary: Register a new worker with a photo
 *     consumes:
 *       - multipart/form-data
 *     parameters:
 *       - in: formData
 *         name: photo
 *         type: file
 *         required: true
 *         description: The photo of the worker taken by admin
 *       - in: formData
 *         name: name
 *         type: string
 *         required: true
 *         description: Name of the worker
 *       - in: formData
 *         name: faceData
 *         type: string
 *         description: Face embeddings generated by AI
 *       - in: formData
 *         name: jobRole
 *         type: string
 *         required: true
 *         description: Job role of the worker
 *       - in: formData
 *         name: place
 *         type: string
 *         required: true
 *         description: Work location or site
 *       - in: formData
 *         name: contactNumber
 *         type: string
 *         required: true
 *         description: Contact number
 *       - in: formData
 *         name: dailyWage
 *         type: number
 *         required: true
 *         description: Daily wage of the worker
 *     responses:
 *       201:
 *         description: Created successfully
 */
router.post('/', upload.single('photo'), workerController.registerWorker);
router.put('/:id', upload.single('photo'), workerController.updateWorker);
router.delete('/:id', workerController.deleteWorker);

module.exports = router;
